###

POST http://localhost:8080/api/v1/users
Content-Type: application/json

{
  "name": "James",
  "surname": "Smith",
  "birthday": "2000-01-31"
}

> {%
    client.test("Request executed successfully", function () {
        client.assert(response.status === 201, "Response status is not 201: " + response.status);
    });
%}

###

POST http://localhost:8080/api/v1/users
Content-Type: application/json

{
  "name": "Nick",
  "surname": "Jackson",
  "birthday": "2001-03-31"
}


> {%
    client.test("Request executed successfully", function () {
        client.assert(response.status === 201, "Response status is not 201: " + response.status);
    });
%}

###

POST http://localhost:8080/api/v1/subscriptions
Content-Type: application/json

{
  "userId": 1
}


> {%
    client.test("Request executed successfully", function () {
        client.assert(response.status === 201, "Response status is not 201: " + response.status);
    });
%}

###

POST http://localhost:8080/api/v1/subscriptions
Content-Type: application/json

{
  "userId": 2
}


> {%
    client.test("Request executed successfully", function () {
        client.assert(response.status === 201, "Response status is not 201: " + response.status);
    });
%}

###

PATCH http://localhost:8080/api/v1/users/1
Content-Type: application/json

{
  "name": "Jack"
}


> {%
    client.test("Request executed successfully", function () {
        client.assert(response.status === 200, "Response status is not 200: " + response.status);
    });
%}

###

PATCH http://localhost:8080/api/v1/users/1
Content-Type: application/json

{
  "birthday": "1977-01-31"
}


> {%
    client.test("Request executed successfully", function () {
        client.assert(response.status === 200, "Response status is not 200: " + response.status);
    });
%}

###

PUT http://localhost:8080/api/v1/users/1
Content-Type: application/json

{
  "name": "Jack",
  "surname": "Daniel",
  "birthday": "1988-01-31"
}


> {%
    client.test("Request executed successfully", function () {
        client.assert(response.status === 200, "Response status is not 200: " + response.status);
    });
%}

###

PUT http://localhost:8080/api/v1/subscriptions/1
Content-Type: application/json

{
  "userId": 2
}


> {%
    client.test("Request executed successfully", function () {
        client.assert(response.status === 200, "Response status is not 200: " + response.status);
    });
%}

###

GET http://localhost:8080/api/v1/users/1
Content-Type: application/json

> {%
    client.test("Request executed successfully", function () {
        client.assert(response.status === 200, "Response status is not 200: " + response.status);
    });
%}

###

GET http://localhost:8080/api/v1/users
Content-Type: application/json

> {%
    client.test("Request executed successfully", function () {
        client.assert(response.status === 200, "Response status is not 200: " + response.status);
    });
%}

###

GET http://localhost:8080/api/v1/subscriptions/1
Content-Type: application/json

> {%
    client.test("Request executed successfully", function () {
        client.assert(response.status === 200, "Response status is not 200: " + response.status);
    });
%}

###

GET http://localhost:8080/api/v1/subscriptions
Content-Type: application/json

> {%
    client.test("Request executed successfully", function () {
        client.assert(response.status === 200, "Response status is not 200: " + response.status);
    });
%}

###

DELETE http://localhost:8080/api/v1/subscriptions/1

> {%
    client.test("Request executed successfully", function () {
        client.assert(response.status === 204, "Response status is not 204: " + response.status);
    });
%}

###

GET http://localhost:8080/api/v1/users
Content-Type: application/json

> {%
    client.test("Request executed successfully", function () {
        client.assert(response.status === 200, "Response status is not 200: " + response.status);
    });
%}

###

GET http://localhost:8080/api/v1/subscriptions
Content-Type: application/json

> {%
    client.test("Request executed successfully", function () {
        client.assert(response.status === 200, "Response status is not 200: " + response.status);
    });
%}

###

DELETE http://localhost:8080/api/v1/users/2

> {%
    client.test("Request executed successfully", function () {
        client.assert(response.status === 204, "Response status is not 204: " + response.status);
    });
%}

###

